Add explicit reference for logger
flaper87/pyhelm pull request #41
Opened 2019-01-08 15:44 UTC by naphta

Just tried to start using this and it seems to be trying to import logger from a global namespace. I've made this explicit to import it from pyhelm itself.

I've only tested this on Python 3 but off the top of my head I don't see any forseen compatibility issues. I'm not sure if there are tests somewhere I can run? I've not gotten my head specifically into it rather fixed the bug my end.

2019-01-09 15:13 UTC, avorima requested changes
Hey @naphta I tested your changes with Python 2.7.15 and the logger import is working as intended.

It seems your decision to switch to the `io` module caused some issues though. Please review my suggestions on how to fix them.

2019-01-09 15:13 UTC, avorima commented on pyhelm/repo.py
> +    from io import StringIO
Use `BytesIO` instead of `StringIO`. `StringIO` requires a unicode string, which `_get_from_repo` doesn't return.

2019-01-09 15:13 UTC, avorima commented on pyhelm/repo.py
> +    import cStringIO as StringIO
The io module was added in Python 2.6 so I'd just remove cStringIO altogether

2019-01-09 15:13 UTC, avorima commented on pyhelm/repo.py
> +                fobj = StringIO.StringIO(
`io.StringIO` (and `io.BytesIO`) is a class and not a module, so call it directly

2019-01-09 20:15 UTC, naphta commented
@avorima I have a few changes "due" I'd been playing around trying to get kubernetes port forwarding support working via web sockets (not straightforward or well supported in python at the moment). Along the way I've made a few tweaks for python 3 though. I'll clean up my code and push it tomorrow.

2019-01-10 15:16 UTC, naphta commented
Made a small mess of merging in some recent changes but there was a decent bit of refactor I ended up doing to better support 3. I also switched over to pathlib for loading the files. I've explicitly referenced the paths being passed in as posix but I don't have a windows machine to test on to be sure.

2019-01-10 16:00 UTC, avorima requested changes
@naphta Looks good, just some small remarks.

I don't see the value in using the `/` operator from pathlib. Using it probably led to the problem with `yaml.load`. Just replace `pathlib.Path(x) / y` with `pathlib.Path(x, y)`

Also please add `pathlib2` to requirements.txt, because it's a not a core module in Python 2.

2019-01-10 16:18 UTC, naphta commented on pyhelm/repo.py
>              try:
Apologies, I did a manual merge against master and didn't spot that change.

2019-01-10 16:19 UTC, naphta commented
I've made the changes now, are there a set of unit tests I can run? I saw there's a tox environment but there's scripts missing to actually execute.

2019-01-10 16:36 UTC, avorima commented on pyhelm/chartbuilder.py
> +        chart_yaml = dotify(yaml.load(pathlib.Path(self.source_directory) / 'Chart.yaml').read_text())
You're still missing a closing parenthesis on this line.

2019-01-31 15:23 UTC, naphta commented
Just done a rebase from master, it was working my end, been using itl ocally in a project.

2020-11-30 18:20 UTC, closed without merging